version: 2.1

parameters:
  node-version:
    type: string
    default: '16.13.0'

commands:
  install_deps:
    description: Install dependencies
    steps:
      - run:
          name: pnpm install
          command: pnpm i --frozen-lockfile
  checkout_submodules:
    description: Checkout git submodules
    steps:
      - run:
          name: checkout submodules
          command: |
            git submodule init
            git submodule update
orbs:
  win: circleci/windows@2.2.0 # The Windows orb give you everything you need to start using the Windows executor.

jobs:
  build-windows:
    executor: win/default
    steps:
      - checkout
      - checkout_submodules
      - run:
          name: Install WiX
          command: choco install wixtoolset --version 3.11.2
      - run:
          name: Install Node.js
          command: |
            nvm install << pipeline.parameters.node-version >>
            nvm use << pipeline.parameters.node-version >>
      - run:
          name: Install pnpm
          command: npm install --global pnpm
      - run:
          name: Check Node.js/pnpm installs
          command: |
            node -v
            pnpm -v
      - install_deps
      - run:
          name: Install Java
          command: |
            curl https://s3.us-west-2.amazonaws.com/public.breakout.jedwards1211/jdk-8u181-windows-x64.zip > jdk-x64.zip
            curl https://s3.us-west-2.amazonaws.com/public.breakout.jedwards1211/jdk-8u181-windows-x86.zip > jdk-x86.zip
            mkdir jdk-x64
            mkdir jdk-x86
            (cd jdk-x64; unzip ../jdk-x64.zip)
            (cd jdk-x86; unzip ../jdk-x86.zip)
          shell: bash.exe
      - run:
          name: Install Maven
          command: |
            curl https://mirror.olnevhost.net/pub/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz > maven.tar.gz
            tar -xzvf maven.tar.gz
          shell: bash.exe
      - run:
          name: Check Java/Maven installs
          command: |
            export JAVA_HOME="$PWD/jdk-x64"
            export MVN_HOME="$PWD/apache-maven-3.6.3"
            export PATH="$JAVA_HOME/bin:$MVN_HOME/bin:/c/Program Files (x86)/WiX Toolset v3.11/bin:$PATH"
            java -version
            javapackager -version
            mvn -v
          shell: bash.exe
      - run:
          name: Get release version
          command: pnpm semantic-release -- --dry-run
          shell: bash.exe
      - run:
          name: Build
          command: |
            export JAVA_HOME="$PWD/jdk-x64"
            export MVN_HOME="$PWD/apache-maven-3.6.3"
            export PATH="$JAVA_HOME/bin:$MVN_HOME/bin:/c/Program Files (x86)/WiX Toolset v3.11/bin:$PATH"
            mvn clean install -Dbreakout.version="$(< version)" -P windows,windows-i586,windows-amd64
            mkdir -p dist/windows
            cp breakout/target/breakout-0.0.0-SNAPSHOT.jar dist/windows/breakout.jar
          shell: bash.exe
      - run:
          name: Package x64
          command: |
            export JAVA_HOME="$PWD/jdk-x64"
            export MVN_HOME="$PWD/apache-maven-3.6.3"
            export PATH="$JAVA_HOME/bin:$MVN_HOME/bin:/c/Program Files (x86)/WiX Toolset v3.11/bin:$PATH"
            javapackager -deploy -native msi -outdir packages -outfile Breakout \
              -srcdir dist/windows -srcfiles breakout.jar \
              -appclass org.breakout.Breakout -name Breakout -title "Breakout Cave Survey" \
              -BappVersion=$(< version) -Bicon=breakout.ico
            cp packages/bundles/Breakout-$(cat version | xargs).msi dist/windows/Breakout-x64.msi
          shell: bash.exe
      - run:
          name: Package x86
          command: |
            export JAVA_HOME="$PWD/jdk-x86"
            export MVN_HOME="$PWD/apache-maven-3.6.3"
            export PATH="$JAVA_HOME/bin:$MVN_HOME/bin:/c/Program Files (x86)/WiX Toolset v3.11/bin:$PATH"
            javapackager -deploy -native msi -outdir packages -outfile Breakout \
              -srcdir dist/windows -srcfiles breakout.jar \
              -appclass org.breakout.Breakout -name Breakout -title "Breakout Cave Survey" \
              -BappVersion=$(< version) -Bicon=breakout.ico
            cp packages/bundles/Breakout-$(cat version | xargs).msi dist/windows/Breakout-x86.msi
          shell: bash.exe
      - store_artifacts:
          path: dist/windows
      - persist_to_workspace:
          root: .
          paths:
            - dist/windows

  build-macos:
    macos:
      xcode: 11.5.0
    steps:
      - checkout
      - checkout_submodules
      - run:
          name: Install Node.js
          command: |
            curl https://nodejs.org/dist/v<< pipeline.parameters.node-version >>/node-v<< pipeline.parameters.node-version >>.pkg > "$HOME/Downloads/node-v<< pipeline.parameters.node-version >>.pkg"
            sudo installer -store -pkg "$HOME/Downloads/node-v<< pipeline.parameters.node-version >>.pkg" -target /
      - run:
          name: Install pnpm
          command: npm install --global pnpm
      - run:
          name: Check Node.js/pnpm installs
          command: |
            node -v
            pnpm -v
      - install_deps
      - run:
          name: Install Java
          command: |
            curl https://s3.us-west-2.amazonaws.com/public.breakout.jedwards1211/jdk-8u181-macosx-x64.dmg > "$HOME/Downloads/jdk-8u181-macosx-x64.dmg"
            hdiutil attach "$HOME/Downloads/jdk-8u181-macosx-x64.dmg"
            sudo installer -pkg /Volumes/JDK\ 8\ Update\ 181/JDK\ 8\ Update\ 181.pkg -target /
            diskutil umount /Volumes/JDK\ 8\ Update\ 181
      - run:
          name: Setup Environment Variables
          command: |
            echo "export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home" >> $BASH_ENV
            echo "export PATH=$JAVA_HOME/bin:$PATH" >> $BASH_ENV
      - run:
          name: Install Maven
          command: |
            curl https://mirror.olnevhost.net/pub/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz > "$HOME/Downloads/apache-maven-3.6.3-bin.tar.gz"
            tar xzvf "$HOME/Downloads/apache-maven-3.6.3-bin.tar.gz"
            echo "export PATH=apache-maven-3.6.3/bin:$PATH" >> $BASH_ENV
      - run:
          name: Check Java/Maven installs
          command: |
            java -version
            javapackager -version
            mvn -v
      - run:
          name: Get release version
          command: pnpm semantic-release -- --dry-run
      - run:
          name: Build
          command: |
            mvn clean install -Dbreakout.version="$(< version)"
            mkdir -p dist/macos
            cp breakout/target/breakout-0.0.0-SNAPSHOT.jar dist/macos/breakout.jar
            mvn clean install -Dbreakout.version="$(< version)" -P osx,windows,windows-i586,windows-amd64,linux,linux-i586,linux-amd64
            cp breakout/target/breakout-0.0.0-SNAPSHOT.jar dist/macos/breakout-all-platforms.jar
      - run:
          name: Package
          command: |
            javapackager -deploy -native image -outdir packages -outfile Breakout \
              -srcdir dist/macos -srcfiles breakout.jar \
              -appclass org.breakout.Breakout -name Breakout -title "Breakout Cave Survey" \
              -BappVersion=$(< version) -Bicon=breakout.icns
            hdiutil create temp.dmg -ov -volname "Breakout" -fs HFS+ -srcfolder packages/bundles
            hdiutil convert temp.dmg -format UDZO -o dist/macos/Breakout.dmg
      - store_artifacts:
          path: dist/macos
      - persist_to_workspace:
          root: .
          paths:
            - dist/macos

  release:
    docker:
      - image: circleci/node:<< pipeline.parameters.node-version >>
    steps:
      - checkout
      - run:
          name: Install pnpm
          command: npm install --global pnpm
      - install_deps
      - attach_workspace:
          at: .
      - run:
          name: Release
          command: semantic-release

workflows:
  version: 2
  build-release:
    jobs:
      - build-windows
      - build-macos
      - release:
          requires:
            - build-windows
            - build-macos
          filters:
            branches:
              only:
                - master
                - next
