version: 2.1

parameters:
  node-version:
    type: string
    default: '16.13.0'

commands:
  install_deps:
    description: Install dependencies
    steps:
      - run:
          name: pnpm
          command: pnpm i --frozen-lockfile

jobs:
  build-macos:
    macos:
      xcode: 11.5.0
    steps:
      - checkout
      - run:
          name: checkout submodules
          command: |
            git submodule init
            git submodule update
      - run:
          name: Install Node.js
          command: |
            curl https://nodejs.org/dist/v<< pipeline.parameters.node-version >>/node-v<< pipeline.parameters.node-version >>.pkg > "$HOME/Downloads/node-v<< pipeline.parameters.node-version >>.pkg"
            sudo installer -store -pkg "$HOME/Downloads/node-v<< pipeline.parameters.node-version >>.pkg" -target /
      - run:
          name: Install pnpm
          command: npm install --global pnpm
      - run:
          name: Check Node.js/pnpm installs
          command: |
            node -v
            pnpm -v
      - install_deps
      - run:
          name: Install Java
          command: |
            curl https://s3.us-west-2.amazonaws.com/public.breakout.jedwards1211/jdk-8u181-macosx-x64.dmg > "$HOME/Downloads/jdk-8u181-macosx-x64.dmg"
            hdiutil attach "$HOME/Downloads/jdk-8u181-macosx-x64.dmg"
            sudo installer -pkg /Volumes/JDK\ 8\ Update\ 181/JDK\ 8\ Update\ 181.pkg -target /
            diskutil umount /Volumes/JDK\ 8\ Update\ 181
      - run:
          name: Setup Environment Variables
          command: |
            echo "export JAVA_HOME=/Library/Java/JavaVirtualMachines/jdk1.8.0_181.jdk/Contents/Home" >> $BASH_ENV
            echo "export PATH=$JAVA_HOME/bin:$PATH" >> $BASH_ENV
      - run:
          name: Install Maven
          command: |
            curl https://mirror.olnevhost.net/pub/apache/maven/maven-3/3.6.3/binaries/apache-maven-3.6.3-bin.tar.gz > "$HOME/Downloads/apache-maven-3.6.3-bin.tar.gz"
            tar xzvf "$HOME/Downloads/apache-maven-3.6.3-bin.tar.gz"
            echo "export PATH=apache-maven-3.6.3/bin:$PATH" >> $BASH_ENV
      - run:
          name: Check Java/Maven installs
          command: |
            java -version
            javapackager -version
            mvn -v
      - run:
          name: Get release version
          command: pnpm semantic-release --dry-run
      - run:
          name: Build
          command: |
            mvn clean install
            mkdir -p dist/macos
            cp breakout/target/breakout-0.0.0-SNAPSHOT.jar dist/macos/breakout.jar
      - run:
          name: Package
          command: |
            javapackager -deploy -native image -outdir packages -outfile Breakout \
              -srcdir dist/macos -srcfiles breakout.jar \
              -appclass org.breakout.Breakout -name Breakout -title "Breakout Cave Survey" \
              -BappVersion=$(< version)
            hdiutil create temp.dmg -ov -volname "Breakout" -fs HFS+ -srcfolder packages/bundles
            hdiutil convert temp.dmg -format UDZO -o dist/macos/Breakout.dmg
      - store_artifacts:
          path: dist/macos/Breakout.dmg
      - persist_to_workspace:
          root: .
          paths:
            - dist/macos/breakout.jar
            - dist/macos/Breakout.dmg

  release:
    docker:
      - image: circleci/node:<< pipeline.parameters.node-version >>
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Release
          command: semantic-release

workflows:
  version: 2
  build-release:
    jobs:
      - build-macos
      - release:
          requires:
            - build-macos
          context: github
          filters:
            branches:
              only: master, next
