settingsDrawerModel:
  cameraView: PERSPECTIVE
  mouseSensitivity: 50
  distRange: 223.394714 to 67078.437500
  paramRange: -109.104469 to 420.554474
  highlightRange: 0.000000 to 1385.827148
surveyDrawerPinned: false
miniSurveyDrawerPinned: false
surveyDrawerMaximized: false
taskListDrawerPinned: false
