settingsDrawerModel:
  cameraView: PERSPECTIVE
  mouseSensitivity: 20
  distRange:
    scale: 0.009970684483228803
    offset: 0.0
  paramRange:
    scale: 0.4
    offset: 0.0
  highlightRange:
    scale: 0.2
    offset: 0.0
