settingsDrawerModel:
  cameraView: PERSPECTIVE
  mouseSensitivity: 20
  distRange:
    scale: 0.0014535268939745284
    offset: 0.0
  paramRange:
    scale: 0.7239550875408881
    offset: 111.95335995092745
  highlightRange:
    scale: 0.19804221343978426
    offset: -31.897105245625426
  filterType: REGEXP
surveyDrawerPinned: false
miniSurveyDrawerPinned: false
taskListDrawerPinned: false
