settingsDrawerModel:
  cameraView: PERSPECTIVE
  mouseSensitivity: 20
  distRange:
    scale: 0.01
    offset: 0.0
  paramRange:
    scale: 0.39211841976276823
    offset: 85.31424999999996
  highlightRange:
    scale: 0.2
    offset: 0.0
  filterType: ALPHA_DESIGNATION
