package org.breakout.wallsimport;

public enum WallsExpectedTypes
{
	UNITS_OPTION, ESCAPED_CHAR, MEASUREMENT, LRUD_MEASUREMENT, END_OF_LINE, VARIANCE, SEGMENT, PREFIX, MACRO_NAME, STATION_NAME, FLAG, DATE, NOTE, QUOTED_TEXT
}
